  version: "3"
  services:
    web:
      build: .
      volumes:
        - .:/app
      depends_on:
        - selenium
      environment:
        - SELENIUM_HOST=selenium-chrome
    selenium:
      image: selenium/standalone-chrome:latest
      ports:
        - 4444:4444
        - 7900:7900 
        # 'secret' password
      shm_size: "2g"


# how to run just type 
#  sudo docker-compose up --build 
#  for browser check localhost:7900 password : secret
#  you will see the borwser script running